version: "3.9"
services:
  jsapi-ws:
    container_name: websocket
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/opt/app/ws
    environment:
      JSAPIWS_PORT: "3001"
      JSAPIWS_RABBITMQ_DIAL: "amqp://jsuser:jspass@localhost:5672/"
    ports:
      - "3001:3001"
